# phpunit-coverage-badge: Github action for generating a phpunit coverage percentage badge
#
# Copyright (c) 2020 Tim Krase
# https://timkrase.de
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

name: 'phpunit-coverage-badge'
author: 'Tim Krase <timkrase@timkrase.de>'
description: 'Creates a code coverage badge from phpunit reports'
branding:
  icon: 'award'
  color: 'gray-dark'
inputs:
  report:
    description: 'The path to the report file generated by PHPUnit.'
    required: false
    default: 'clover.xml'
  report_type:
    description: 'The type of the generated report. Currently supported: clover, html.'
    required: false
    default: 'clover'
  coverage_badge_path:
    description: 'The path inside the repository where the created badge should be saved. Can be anywhere except inside the .github folder.'
    required: false
    default: 'coverage_badge.svg'
  push_badge:
    description: 'Defines whether the badge will be committed and pushed to the repository.'
    required: false
    default: 'false'
  repo_token:
    description: 'Token to push the badge into the repository. Can be supplied with $/{{ secrets.GITHUB_TOKEN }} (without the "/").'
    required: false
    default: 'NOT_SUPPLIED'
  commit_message:
    description: 'Commit message that will be used to commit the updated badge and clover file.'
    required: false
    default: 'Update code coverage badge'
  commit_email:
    description: 'Email that will be used for the commit.'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  commit_name:
    description: 'Name that will be used for the commit.'
    required: false
    default: 'Github Actions Bot'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/timkrase/phpunit-coverage-badge:v1.0.0'
  args:
    - ${{ inputs.clover-report }}
    - ${{ inputs.coverage-badge-path }}
    - ${{ inputs.repo_token }}
    - ${{ inputs.commit_message }}
    - ${{ inputs.commit_email }}
    - ${{ inputs.commit_name }}
